In [1]:
import matplotlib.pyplot as plt
import numpy as np
from os import listdir

font_size = 30
font_size_ticks = 25

np.set_printoptions(precision=5)

def process_name(x):
    x = x[14:]
    x = x[:-7]
    x = x.translate(str.maketrans('','','_1234567890'))
    return x[2:] + ", " + x[:2]

file_path = "./data/weather/hourly_precipitation_2015.npy"

# data_matrix contains precipitation data from 134 stations (each station is a column)
data_matrix = np.load(file_path)

print(data_matrix.shape) 
print(data_matrix[25:35,:10])

(8760, 134)
[[0.  1.  0.3 0.7 0.  0.2 1.  0.2 0.  0.4]
 [0.  0.4 0.2 0.3 0.  0.6 1.9 1.1 0.  0. ]
 [0.  0.6 0.  0.  0.  0.2 0.7 1.1 0.  0. ]
 [0.  0.2 0.  0.  0.  0.  0.4 0.2 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.7 0.  0.  0. ]
 [0.  0.  0.6 0.2 0.  0.  0.5 0.2 0.  0.7]
 [0.  0.  0.9 0.9 0.  0.  1.3 0.  0.  0.6]
 [0.  0.3 0.6 1.2 0.  0.4 1.9 0.  0.  0.2]
 [0.  0.  0.3 0.  0.  0.6 0.6 0.4 0.  0.6]
 [0.  0.  0.5 0.  0.  0.2 0.5 0.6 0.  0.3]]


In [2]:
# We select three stations to study, stations contains the corresponding indices in data_matrix
# 24: Bodega, CA
# 99: Coos Bay, OR
# 102: Riley, OR
stations = [24,99,102]

In [3]:
# Compute joint pmf of three Bernoulli random variables indicating whether it rains (1) or not (0)
# in Bodega, Coos Bay and Riley
def compute_joint_pmf(station_1,station_2,station_3,data_matrix):
    # INSERT YOUR CODE HERE

counts,joint_pmf = compute_joint_pmf(stations[0],stations[1],stations[2],data_matrix)
print(counts)
print(joint_pmf)

IndentationError: expected an indented block (<ipython-input-3-1b554138579a>, line 6)

In [4]:
# Compute marginal pmf of each of the Bernoulli random variables 
def marginal_1_station(joint_pmf):
    # INSERT YOUR CODE HERE

marginal_pmf_1,marginal_pmf_2,marginal_pmf_3 = marginal_1_station(joint_pmf)
print(marginal_pmf_1)
print(marginal_pmf_2)
print(marginal_pmf_3)

vals = [0,1]
ymax = 1.0
xmin = -0.6
xmax = 1.6
plt.figure(figsize=(6,9))
plt.bar(vals,marginal_pmf_1, width = 0.5, color = "lightgray", edgecolor="black",linewidth = 2)
plt.xticks(np.arange(0, 1+1, 1))
plt.xticks(fontsize=font_size_ticks) 
plt.yticks(fontsize=font_size_ticks)
plt.ylim([0,ymax])
plt.xlim([xmin,xmax])
plt.ylabel("Probability mass function",fontsize=font_size,labelpad = 30)
plt.xlabel("Precipitation in Bodega",fontsize=font_size,labelpad = 15)
plt.savefig('plots/precipitation_marginal_pmf_1.pdf',bbox_inches="tight")

plt.figure(figsize=(6,9))
plt.bar(vals,marginal_pmf_2, width = 0.5, color = "lightgray", edgecolor="black",linewidth = 2)
plt.xticks(np.arange(0, 1+1, 1))
plt.xticks(fontsize=font_size_ticks) 
plt.yticks(fontsize=font_size_ticks)
plt.ylim([0,ymax])
plt.xlim([xmin,xmax])
plt.ylabel("Probability mass function",fontsize=font_size,labelpad = 30)
plt.xlabel("Precipitation in Coos Bay",fontsize=font_size,labelpad = 15)
plt.savefig('plots/precipitation_marginal_pmf_2.pdf',bbox_inches="tight")

plt.figure(figsize=(6,9))
plt.bar(vals,marginal_pmf_3, width = 0.5, color = "lightgray", edgecolor="black",linewidth = 2)
plt.xticks(np.arange(0, 1+1, 1))
plt.xticks(fontsize=font_size_ticks) 
plt.yticks(fontsize=font_size_ticks)
plt.ylim([0,ymax])
plt.xlim([xmin,xmax])
plt.ylabel("Probability mass function",fontsize=font_size,labelpad = 30)
plt.xlabel("Precipitation in Riley",fontsize=font_size,labelpad = 15)
plt.savefig('plots/precipitation_marginal_pmf_3.pdf',bbox_inches="tight")

IndentationError: expected an indented block (<ipython-input-4-6cc5180980e2>, line 5)

In [5]:
# Compute marginal joint pmf of each pair of the Bernoulli random variables 
def marginal_2_stations(joint_pmf):
    # INSERT YOUR CODE HERE

marginal_pmf_12,marginal_pmf_13,marginal_pmf_23 = marginal_2_stations(joint_pmf)

print(marginal_pmf_12)
print(marginal_pmf_13)
print(marginal_pmf_23)

IndentationError: expected an indented block (<ipython-input-5-7d167c12dd68>, line 5)

In [6]:
# Compute conditional pmf of each of the Bernoulli random variables given the other two 
def conditional_1_station_given_2(joint_pmf):
    # INSERT YOUR CODE HERE

cond_1_given_23,cond_2_given_13,cond_3_given_12 = conditional_1_station_given_2(joint_pmf)

for ind_2 in range(2):
    for ind_3 in range(2):
        print(cond_1_given_23[ind_2][ind_3])
        plt.figure(figsize=(6,9))
        plt.bar(vals,cond_1_given_23[ind_2][ind_3], width = 0.5, color = "lightgray", edgecolor="black",linewidth = 2)
        plt.xticks(np.arange(0, 1+1, 1))
        plt.xticks(fontsize=font_size_ticks) 
        plt.yticks(fontsize=font_size_ticks)
        plt.ylim([0,ymax])
        plt.xlim([xmin,xmax])
        plt.ylabel("Conditional probability mass function",fontsize=font_size,labelpad = 30)
        plt.xlabel("Precipitation in Bodega",fontsize=font_size,labelpad = 15)
        plt.savefig('plots/precipitation_cond_pmf_1_given_2eq'+str(ind_2)+'_3eq'+str(ind_3)+'.pdf',bbox_inches="tight")

for ind_1 in range(2):
    for ind_3 in range(2):
        print(cond_2_given_13[ind_1][ind_3])
        plt.figure(figsize=(6,9))
        plt.bar(vals,cond_2_given_13[ind_1][ind_3], width = 0.5, color = "lightgray", edgecolor="black",linewidth = 2)
        plt.xticks(np.arange(0, 1+1, 1))
        plt.xticks(fontsize=font_size_ticks) 
        plt.yticks(fontsize=font_size_ticks)
        plt.ylim([0,ymax])
        plt.xlim([xmin,xmax])
        plt.ylabel("Conditional probability mass function",fontsize=font_size,labelpad = 30)
        plt.xlabel("Precipitation in Coos Bay",fontsize=font_size,labelpad = 15)
        plt.savefig('plots/precipitation_cond_pmf_2_given_1eq'+str(ind_1)+'_3eq'+str(ind_3)+'.pdf',bbox_inches="tight")

for ind_1 in range(2):
    for ind_2 in range(2):
        print(cond_3_given_12[ind_1][ind_2])
        plt.figure(figsize=(6,9))
        plt.bar(vals,cond_3_given_12[ind_1][ind_2], width = 0.5, color = "lightgray", edgecolor="black",linewidth = 2)
        plt.xticks(np.arange(0, 1+1, 1))
        plt.xticks(fontsize=font_size_ticks) 
        plt.yticks(fontsize=font_size_ticks)
        plt.ylim([0,ymax])
        plt.xlim([xmin,xmax])
        plt.ylabel("Conditional probability mass function",fontsize=font_size,labelpad = 30)
        plt.xlabel("Precipitation in Riley",fontsize=font_size,labelpad = 15)
        plt.savefig('plots/precipitation_cond_pmf_3_given_1eq'+str(ind_1)+'_2eq'+str(ind_2)+'.pdf',bbox_inches="tight")


IndentationError: expected an indented block (<ipython-input-6-42cccff2e93d>, line 5)

In [7]:
# Compute conditional joint pmf of each pair of the Bernoulli random variables given the other one
def conditional_2_stations_given_1(joint_pmf):
    # INSERT YOUR CODE HERE

cond_12_given_3,cond_13_given_2,cond_23_given_1 = conditional_2_stations_given_1(joint_pmf)

for ind in range(2):
    print(cond_12_given_3[ind])
for ind in range(2):
    print(cond_13_given_2[ind])
for ind in range(2):
    print(cond_23_given_1[ind])

IndentationError: expected an indented block (<ipython-input-7-1feaffe6bf6d>, line 5)

In [8]:
# Compute conditional pmf of each Bernoulli random variable given each of the other ones 
# (i.e. Bodega just conditioned on Coos Bay, Bodega just conditioned on Riley, etc.)
# Use a dictionary to save the conditional pmfs, for example cond_1["2"] should contain the conditional of the
# first random variable (Bodega)
def conditional_1_station_given_1_station(joint_pmf):
    # INSERT YOUR CODE HERE

cond_1,cond_2,cond_3 = conditional_1_station_given_1_station(joint_pmf)

for given in ["2","3"]:
    for ind in range(2):
        plt.figure(figsize=(6,9))
        plt.bar(vals,cond_1[given][ind], width = 0.5, color = "lightgray", edgecolor="black",linewidth = 2)
        plt.xticks(np.arange(0, 1+1, 1))
        plt.xticks(fontsize=font_size_ticks) 
        plt.yticks(fontsize=font_size_ticks)
        plt.ylim([0,ymax])
        plt.xlim([xmin,xmax])
        plt.ylabel("Conditional probability mass function",fontsize=font_size,labelpad = 30)
        plt.xlabel("Precipitation in Bodega",fontsize=font_size,labelpad = 15)
        plt.savefig('plots/precipitation_cond_pmf_1_given_'+ given + 'eq'+str(ind)+'.pdf',bbox_inches="tight")
        
for given in ["1","3"]:
    for ind in range(2):
        plt.figure(figsize=(6,9))
        plt.bar(vals,cond_2[given][ind], width = 0.5, color = "lightgray", edgecolor="black",linewidth = 2)
        plt.xticks(np.arange(0, 1+1, 1))
        plt.xticks(fontsize=font_size_ticks) 
        plt.yticks(fontsize=font_size_ticks)
        plt.ylim([0,ymax])
        plt.xlim([xmin,xmax])
        plt.ylabel("Conditional probability mass function",fontsize=font_size,labelpad = 30)
        plt.xlabel("Precipitation in Coos Bay",fontsize=font_size,labelpad = 15)
        plt.savefig('plots/precipitation_cond_pmf_2_given_'+ given + 'eq'+str(ind)+'.pdf',bbox_inches="tight")

for given in ["1","2"]:
    for ind in range(2):
        plt.figure(figsize=(6,9))
        plt.bar(vals,cond_3[given][ind], width = 0.5, color = "lightgray", edgecolor="black",linewidth = 2)
        plt.xticks(np.arange(0, 1+1, 1))
        plt.xticks(fontsize=font_size_ticks) 
        plt.yticks(fontsize=font_size_ticks)
        plt.ylim([0,ymax])
        plt.xlim([xmin,xmax])
        plt.ylabel("Conditional probability mass function",fontsize=font_size,labelpad = 30)
        plt.xlabel("Precipitation in Riley",fontsize=font_size,labelpad = 15)
        plt.savefig('plots/precipitation_cond_pmf_3_given_'+ given + 'eq'+str(ind)+'.pdf',bbox_inches="tight")


IndentationError: expected an indented block (<ipython-input-8-4569f459f189>, line 8)